CREATE USER
    c##juanj
IDENTIFIED BY
    G3R4RDI
DEFAULT TABLESPACE
    USERS
QUOTA UNLIMITED ON
    USERS;

GRANT CONNECT, RESOURCE TO c##juanj;

-- Crear Tablas --

-- CUSTOMERS --
CREATE TABLE CUSTOMERS (
  ID INTEGER CONSTRAINT customer_id_pk PRIMARY KEY,
  DPI NUMBER(13,0) CONSTRAINT customer_dpi_nn NOT NULL,
  NAME VARCHAR(256) CONSTRAINT customer_name_nn NOT NULL,
  LASTNAME VARCHAR(256) CONSTRAINT customer_lastname_nn NOT NULL,
  EMAIL VARCHAR(256) CONSTRAINT customer_email_uk UNIQUE NOT NULL ,
  PASSWORD VARCHAR(256) CONSTRAINT customer_password_nn NOT NULL,
  PHONE INTEGER CONSTRAINT customer_phone_nn NOT NULL ,
  STATUS VARCHAR(10) CONSTRAINT customer_status_ch CHECK (STATUS IN ('true', 'false')),
  REGISTER TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONFIRMED_EMAIL VARCHAR(10) CONSTRAINT customer_confirm_email_ck CHECK (CONFIRMED_EMAIL IN ('true', 'false')),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ADDRESS --
CREATE TABLE  ADDRESSES (
    ID INTEGER CONSTRAINT address_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT address_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    ADDRESS VARCHAR(256) CONSTRAINT address_address_nn NOT NULL ,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_METHOD --
CREATE TABLE PAYMENT_METHOD(
    ID INTEGER CONSTRAINT payment_m_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT payment_m_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    TYPE VARCHAR(256) CONSTRAINT payment_m_type_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


