CREATE USER
    c##juanj
IDENTIFIED BY
    G3R4RDI
DEFAULT TABLESPACE
    USERS
QUOTA UNLIMITED ON
    USERS;

GRANT CONNECT, RESOURCE TO c##juanj;

-- 1.CUSTOMERS --
CREATE TABLE CUSTOMERS (
  ID INTEGER CONSTRAINT customer_id_pk PRIMARY KEY,
  DPI NUMBER(13,0) CONSTRAINT customer_dpi_nn NOT NULL,
  NAME VARCHAR(256) CONSTRAINT customer_name_nn NOT NULL,
  LASTNAME VARCHAR(256) CONSTRAINT customer_lastname_nn NOT NULL,
  EMAIL VARCHAR(256) CONSTRAINT customer_email_uk UNIQUE NOT NULL ,
  PASSWORD VARCHAR(256) CONSTRAINT customer_password_nn NOT NULL,
  PHONE INTEGER CONSTRAINT customer_phone_nn NOT NULL ,
  STATUS VARCHAR(10) CONSTRAINT customer_status_ch CHECK (STATUS IN ('true', 'false')),
  REGISTER TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONFIRMED_EMAIL VARCHAR(10) CONSTRAINT customer_confirm_email_ck CHECK (CONFIRMED_EMAIL IN ('true', 'false')),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--2.ADDRESS --
CREATE TABLE  ADDRESSES (
    ID INTEGER CONSTRAINT address_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT address_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    ADDRESS VARCHAR(256) CONSTRAINT address_address_nn NOT NULL ,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--3.PAYMENT_METHOD
CREATE TABLE PAYMENT_METHOD(
    ID INTEGER CONSTRAINT payment_m_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT payment_m_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    TYPE VARCHAR(256) CONSTRAINT payment_m_type_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--4.CATEGORY --
CREATE TABLE CATEGORY(
    ID INTEGER CONSTRAINT category_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT category_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--5.PRODUCTS --
CREATE TABLE PRODUCTS(
    ID INTEGER CONSTRAINT product_id_pk PRIMARY KEY,
    SKU VARCHAR(8) CONSTRAINT product_sku_nn NOT NULL ,
    NAME VARCHAR(256) CONSTRAINT product_name_nn NOT NULL,
    PRICE NUMBER(38,2) CONSTRAINT product_price_nn NOT NULL,
    SLUG VARCHAR(256) CONSTRAINT product_slug_nn NOT NULL,
    DESCRIPTION VARCHAR(512) CONSTRAINT product_description_nn NOT NULL,
    ACTIVE VARCHAR(5) CONSTRAINT products_active_ck CHECK ( ACTIVE in ('TRUE','FALSE')),
    CATEGORY_ID INTEGER CONSTRAINT product_category_id_fk REFERENCES CATEGORY(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--6.IMAGES --
CREATE TABLE IMAGES(
    ID INTEGER CONSTRAINT imgs_id_pk PRIMARY KEY,
    ID_PRODUCT INTEGER CONSTRAINT imgs_id_product_fk REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    LINK varchar(256) CONSTRAINT imgs_link_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--7.BRANCHES --
CREATE TABLE BRANCHES(
    ID INTEGER CONSTRAINT branch_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT branch_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--8.INVENTORY --
CREATE TABLE INVENTORY(
    ID INTEGER CONSTRAINT inventory_id_pk PRIMARY KEY,
    ID_BRANCH INTEGER CONSTRAINT inventory_id_branch_fk REFERENCES BRANCHES(ID) ON DELETE CASCADE,
    ID_PRODUCT INTEGER CONSTRAINT inventory_id_product_fk REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INTEGER CONSTRAINT inventory_quantity_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--9.CARRIER --
CREATE TABLE CARRIERS(
    ID INTEGER CONSTRAINT carriers_id_pk PRIMARY KEY,
    NAME_CARRIER VARCHAR(256) CONSTRAINT carriers_name_carrier_nn NOT NULL ,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--10.PURCHASE_ORDERS --
CREATE TABLE PURCHASE_ORDERS(
    ID INTEGER CONSTRAINT purchase_order_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER  CONSTRAINT purchase_order_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--11.SHIPMENTS --
CREATE TABLE SHIPMENTS(
    ID INTEGER CONSTRAINT shipments_id_pk PRIMARY KEY,
    ID_ORDER INTEGER CONSTRAINT shipments_id_order_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_CARRIER INTEGER CONSTRAINT shipments_id_carrier_fk REFERENCES CARRIERS(ID) ON DELETE CASCADE,
    STATUS VARCHAR(25) CONSTRAINT shipments_status_ck CHECK ( STATUS in ('DELIVERED','FAILED','COMMING')),
    ADDRESS VARCHAR(256) CONSTRAINT shipments_address_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--12.PAYMENTS --
CREATE TABLE PAYMENTS(
    ID INTEGER CONSTRAINT payment_id_pk PRIMARY KEY,
    ID_PURCHASE_ORDER INTEGER CONSTRAINT payment_id_purchase_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_PAYMENT_METHOD INTEGER CONSTRAINT payment_id_method_fk REFERENCES PAYMENT_METHOD(ID) ON DELETE SET NULL ,
    STATUS VARCHAR(15) CONSTRAINT payment_status_ck CHECK ( STATUS IN ('PAID','PENDING','FAILED')),
    AMOUNT NUMBER(38,2) CONSTRAINT payment_amount_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--13.ROLE --
CREATE TABLE JOB_TITLE(
    ID INTEGER CONSTRAINT job_title_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT job_title_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);



--14.DEPARTMENT --
CREATE TABLE DEPARTMENT(
    ID INTEGER CONSTRAINT department_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT department_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--15.WORKERS --
CREATE TABLE WORKERS(
    ID INTEGER CONSTRAINT worker_id_pk PRIMARY KEY,
    DPI NUMBER(13,0) CONSTRAINT worker_dpi_un UNIQUE,
    NAME VARCHAR(256) CONSTRAINT worker_name_nn NOT NULL,
    LASTNAME VARCHAR(256) CONSTRAINT worker_lastname_nn NOT NULL,
    PHONE INTEGER CONSTRAINT worker_phone_nn NOT NULL,
    EMAIL VARCHAR(256) CONSTRAINT worker_email_nn   NOT NULL,
    ID_JOB_TITLE INTEGER CONSTRAINT worker_id_job_title_fk REFERENCES JOB_TITLE(ID) ON DELETE SET NULL,
    ID_DEPARTMENT INTEGER CONSTRAINT worker_id_department REFERENCES DEPARTMENT(ID) ON DELETE SET NULL,
    STATUS VARCHAR(10) CONSTRAINT worker_status_ck CHECK ( status in ('TRUE','FALSE')),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--16.LIST_PRODUCTS --
CREATE TABLE LIST_PRODUCTS(
    ID INTEGER CONSTRAINT list_products_id_pk PRIMARY KEY,
    ID_ORDER_PURCHASE INTEGER CONSTRAINT list_product_id_order_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_PRODUCT INTEGER CONSTRAINT list_product_id_product_fk REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INTEGER CONSTRAINT list_product_quantity_nn NOT NULL,
    PRICE NUMBER(38,2) CONSTRAINT list_product_price_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--17.RETURNS --
CREATE TABLE RETURNS(
    ID INTEGER CONSTRAINT return_id_pk PRIMARY KEY,
    ID_ORDER INTEGER CONSTRAINT return_id_order_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_PRODUCT INTEGER CONSTRAINT return_id_product_fk REFERENCES PRODUCTS(ID),
    DESCRIPTION VARCHAR(512) CONSTRAINT return_description_nn NOT NULL,
    STATUS VARCHAR(15) CONSTRAINT return_status_ck CHECK ( STATUS in('PENDING','APROVED','REQUESTED','REJECTED')),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--18.TRANSFERS --
CREATE TABLE TRANSFERS(
    ID INTEGER CONSTRAINT transfer_id_pk PRIMARY KEY,
    ID_LOCATION_ORIGIN INTEGER CONSTRAINT transfer_id_origin REFERENCES BRANCHES(ID) ON DELETE CASCADE,
    ID_LOCATION_DESTINY INTEGER CONSTRAINT transfer_id_destiny REFERENCES BRANCHES(ID) ON DELETE CASCADE,
    STATUS VARCHAR(15) CONSTRAINT transfer_status_ck CHECK (STATUS in ('APPROVED','REJECTED','REQUESTED','PENDING')),
    DATE_ARRIVE TIMESTAMP WITH TIME ZONE CONSTRAINT transfer_date_arrive_nn NOT NULL,
    REQUEST_AT TIMESTAMP WITH TIME ZONE CONSTRAINT transfer_request_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

commit;

SELECT *  FROM PAYMENT_METHOD;
