CREATE USER
    c##juanj
IDENTIFIED BY
    G3R4RDI
DEFAULT TABLESPACE
    USERS
QUOTA UNLIMITED ON
    USERS;

GRANT CONNECT, RESOURCE TO c##juanj;

-- CUSTOMERS --
CREATE TABLE CUSTOMERS (
  ID INTEGER CONSTRAINT customer_id_pk PRIMARY KEY,
  DPI NUMBER(13,0) CONSTRAINT customer_dpi_nn NOT NULL,
  NAME VARCHAR(256) CONSTRAINT customer_name_nn NOT NULL,
  LASTNAME VARCHAR(256) CONSTRAINT customer_lastname_nn NOT NULL,
  EMAIL VARCHAR(256) CONSTRAINT customer_email_uk UNIQUE NOT NULL ,
  PASSWORD VARCHAR(256) CONSTRAINT customer_password_nn NOT NULL,
  PHONE INTEGER CONSTRAINT customer_phone_nn NOT NULL ,
  STATUS VARCHAR(10) CONSTRAINT customer_status_ch CHECK (STATUS IN ('true', 'false')),
  REGISTER TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONFIRMED_EMAIL VARCHAR(10) CONSTRAINT customer_confirm_email_ck CHECK (CONFIRMED_EMAIL IN ('true', 'false')),
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ADDRESS --
CREATE TABLE  ADDRESSES (
    ID INTEGER CONSTRAINT address_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT address_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    ADDRESS VARCHAR(256) CONSTRAINT address_address_nn NOT NULL ,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENT_METHOD
CREATE TABLE PAYMENT_METHOD(
    ID INTEGER CONSTRAINT payment_m_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER CONSTRAINT payment_m_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    TYPE VARCHAR(256) CONSTRAINT payment_m_type_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CATEGORY --
CREATE TABLE CATEGORY(
    ID INTEGER CONSTRAINT category_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT category_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PRODUCTS --
CREATE TABLE PRODUCTS(
    ID INTEGER CONSTRAINT product_id_pk PRIMARY KEY,
    SKU VARCHAR(8) CONSTRAINT product_sku_nn NOT NULL ,
    NAME VARCHAR(256) CONSTRAINT product_name_nn NOT NULL,
    PRICE NUMBER(38,2) CONSTRAINT product_price_nn NOT NULL,
    SLUG VARCHAR(256) CONSTRAINT product_slug_nn NOT NULL,
    DESCRIPTION VARCHAR(512) CONSTRAINT product_description_nn NOT NULL,
    ACTIVE VARCHAR(5) CONSTRAINT products_active_ck CHECK ( ACTIVE in ('TRUE','FALSE')),
    CATEGORY_ID INTEGER CONSTRAINT product_category_id_fk REFERENCES CATEGORY(ID) ON DELETE SET NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- IMAGES --
CREATE TABLE IMAGES(
    ID INTEGER CONSTRAINT imgs_id_pk PRIMARY KEY,
    ID_PRODUCT INTEGER CONSTRAINT imgs_id_product_fk REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    LINK varchar(256) CONSTRAINT imgs_link_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- BRANCHES --
CREATE TABLE BRANCHES(
    ID INTEGER CONSTRAINT branch_id_pk PRIMARY KEY,
    NAME VARCHAR(256) CONSTRAINT branch_name_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- INVENTORY --
CREATE TABLE INVENTORY(
    ID INTEGER CONSTRAINT inventory_id_pk PRIMARY KEY,
    ID_BRANCH INTEGER CONSTRAINT inventory_id_branch_fk REFERENCES BRANCHES(ID) ON DELETE CASCADE,
    ID_PRODUCT INTEGER CONSTRAINT inventory_id_product_fk REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    QUANTITY INTEGER CONSTRAINT inventory_quantity_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- CARRIER --
CREATE TABLE CARRIERS(
    ID INTEGER CONSTRAINT carriers_id_pk PRIMARY KEY,
    NAME_CARRIER VARCHAR(256) CONSTRAINT carriers_name_carrier_nn NOT NULL ,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PURCHASE_ORDERS --
CREATE TABLE PURCHASE_ORDERS(
    ID INTEGER CONSTRAINT purchase_order_id_pk PRIMARY KEY,
    ID_CUSTOMER INTEGER  CONSTRAINT purchase_order_id_customer_fk REFERENCES CUSTOMERS(ID) ON DELETE CASCADE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- SHIPMENTS --
CREATE TABLE SHIPMENTS(
    ID INTEGER CONSTRAINT shipments_id_pk PRIMARY KEY,
    ID_ORDER INTEGER CONSTRAINT shipments_id_order_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_CARRIER INTEGER CONSTRAINT shipments_id_carrier_fk REFERENCES CARRIERS(ID) ON DELETE CASCADE,
    STATUS VARCHAR(25) CONSTRAINT shipments_status_ck CHECK ( STATUS in ('DELIVERED','FAILED','COMMING')),
    ADDRESS VARCHAR(256) CONSTRAINT shipments_address_nn NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- PAYMENTS
CREATE TABLE PAYMENTS(
    ID INTEGER CONSTRAINT payment_id_pk PRIMARY KEY,
    ID_PURCHASE_ORDER INTEGER CONSTRAINT payment_id_purchase_fk REFERENCES PURCHASE_ORDERS(ID) ON DELETE CASCADE,
    ID_PAYMENT_METHOD INTEGER CONSTRAINT payment_id_method_fk REFERENCES PAYMENT_METHOD(ID) ON DELETE SET NULL ,
    STATUS VARCHAR(15) CONSTRAINT payment_status_ck CHECK ( STATUS IN ('PAID','PENDING','FAILED')),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP

);



commit;

SELECT *  FROM PAYMENT_METHOD;
