services:
  #oracle-database

  db:
    image:  container-registry.oracle.com/database/free:latest
    container_name: "SBD1_P1_201900532"
    ports:
      - 1522:1521
    environment:
      - ORACLE_PWD=G3R4RDI
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true 
      - ENABLE_FORCE_LOGGING=true 
      - TZ=America/Guatemala
    volumes:
      - ./oracle-db:/opt/oracle/oradata

  #Backend

  #Volumes
volumes:
  oracle-db:
    external: true